"""init

Revision ID: 92d1edb05f69
Revises:
Create Date: 2026-05-08 17:36:35.116990

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op
from app.utils.database import LibSerial

# revision identifiers, used by Alembic.
revision: str = "92d1edb05f69"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "books",
        sa.Column("serial_number", LibSerial(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("author", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("serial_number"),
    )
    op.create_table(
        "users",
        sa.Column("library_card_id", LibSerial(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("library_card_id"),
    )
    op.create_table(
        "borrowings",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("book_serial", LibSerial(), nullable=False),
        sa.Column("user_serial", LibSerial(), nullable=False),
        sa.Column("borrowed_at", sa.DateTime(), nullable=False),
        sa.Column("returned_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["book_serial"],
            ["books.serial_number"],
        ),
        sa.ForeignKeyConstraint(["user_serial"], ["users.library_card_id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("borrowings")
    op.drop_table("users")
    op.drop_table("books")
    # ### end Alembic commands ###
